services:

  aviation:
    build:
      context: ./aviation
      dockerfile: Dockerfile
    container_name: "aviation_service"
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - aviation/.env
    restart: on-failure
    networks:
      - aviation-net

  database:
    image: postgres:15-alpine
    container_name: "database"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aviation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - aviation-net

  tickets:
    build:
      context: ./tickets
      dockerfile: Dockerfile
    container_name: "tickets_pdf_service"
    ports:
      - "8000:8000"
    volumes:
      - ./tickets:/app
    env_file:
      - ./tickets/.env
    restart: unless-stopped
    networks:
      - aviation-net

  frontend:
    build:
      context: ./aviation-frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    ports:
      - "5173:80"
    depends_on:
      - aviation
    restart: unless-stopped
    networks:
      - aviation-net

  minio:
    image: minio/minio
    container_name: "s3"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - aviation-net

  redis:
    container_name: "redis"
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - aviation-net

volumes:
  postgres_data:
  minio_data:

networks:
  aviation-net:
    driver: bridge