ALTER TABLE tickets ADD COLUMN IF NOT EXISTS seat_number VARCHAR(10);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS class VARCHAR(10);
ALTER TABLE tickets ADD COLUMN IF NOT EXISTS price NUMERIC(10,2);
ALTER TABLE tickets DROP COLUMN IF EXISTS seat_id;
DROP TABLE IF EXISTS seats;
ALTER TABLE flights ADD COLUMN IF NOT EXISTS price NUMERIC(10,2);
ALTER TABLE flights ADD COLUMN IF NOT EXISTS available_seats INT;
